export const TOOLS = [
  {
    id: 'apify',
    title: 'Local Data Research',
    description: 'AI-powered market research — finds target companies by location, industry, and size.',
    icon: 'travel_explore',
    iconBg: '#ff6b35',
    iconColor: '#ff6b35',
    dots: ['#ff6b35', '#ffa07a', '#ffd0b8'],
    credits: 8,
    category: 'Data Research',
    to: '/tools/apify',
  },
  {
    id: 'salessql',
    title: 'Contact Enrichment Linkedin_url',
    description: 'Search and extract B2B sales data using smart SQL-style queries across business databases.',
    icon: 'manage_search',
    iconBg: '#4f7cff',
    iconColor: '#4f7cff',
    dots: ['#4f7cff', '#6f9fff', '#b8ccff'],
    credits: 5,
    category: 'Data Research',
    to: '/tools/salessql',
  },
  {
    id: 'email-extractor',
    title: 'Email Extractor',
    description: 'Extract verified email addresses from websites, domains, and online sources instantly.',
    icon: 'alternate_email',
    iconBg: '#8b5cf6',
    iconColor: '#8b5cf6',
    dots: ['#8b5cf6', '#a78bfa', '#ddd6fe'],
    credits: 4,
    category: 'Data Research',
    to: '/tools/email-extractor',
  },
  {
    id: 'data-scraper',
    title: 'Data Scraper',
    description: 'Scrape and extract structured data from websites and online sources at scale.',
    icon: 'data_object',
    iconBg: '#f59e0b',
    iconColor: '#f59e0b',
    dots: ['#f59e0b', '#fbbf24', '#fde68a'],
    credits: 5,
    category: 'Data Research',
    to: '/tools/data-scraper',
  },
  {
    id: 'icp-builder',
    title: 'ICP Builder',
    description: 'Build your Ideal Customer Profile with AI — define, refine and target your perfect audience.',
    icon: 'people_alt',
    iconBg: '#0f766e',
    iconColor: '#0f766e',
    dots: ['#0f766e', '#14b8a6', '#99f6e4'],
    credits: 5,
    category: 'Data Research',
    to: '/tools/icp-builder',
  },
  {
    id: 'linkedin-scraper',
    title: 'LinkedIn Scraper',
    description: 'Scrape LinkedIn profiles, company pages, and posts to extract structured B2B data at scale.',
    icon: 'linked_camera',
    iconBg: '#0a66c2',
    iconColor: '#0a66c2',
    dots: ['#0a66c2', '#2d8cdb', '#a8d4f5'],
    credits: 6,
    category: 'Data Research',
    to: '/tools/linkedin-scraper',
  },
  {
    id: 'prospeo',
    title: 'Contact Enrichment',
    description: 'Find verified prospect contact data including emails, job titles, and LinkedIn profiles.',
    icon: 'person_search',
    iconBg: '#10b981',
    iconColor: '#10b981',
    dots: ['#10b981', '#34d399', '#a7f3d0'],
    credits: 6,
    category: 'Data Research',
    to: '/tools/prospeo',
  },
]

export const CATEGORIES = ['All', 'Data Research', 'Image Generation', 'Model 3', 'Model 4']
